- name: Installing NVM Version 0.33.2
  hosts: all
  become: yes
  tasks:
   - name: Install nvm
     shell: curl https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
   - name: Source nvm in ~/.profile
     sudo: yes
     lineinfile:
       dest=~/.profile
       line="source ~/.nvm/nvm.sh"
       create=yes

