---
- name: Install Openssl Latest
  hosts: all
  become: yes
  tasks:
    - name: Download Openssl
      command: wget https://www.openssl.org/source/openssl-1.1.1.tar.gz
    - name: Extart Openssl
      command: tar xvf openssl-1.1.1.tar.gz
    - name: Open
      command: chdir=/home/ubuntu/openssl-1.1.1 sudo ./config -Wl,--enable-new-dtags,-rpath,'$(LIBRPATH)'
